language: perl6
install:
- rakudobrew build-panda
- panda --notests installdeps .
script:
- perl6 -MPanda::Builder -e 'Panda::Builder.build($*CWD)'
- echo Running spesh enabled && PERL6LIB=$PWD/blib/lib prove -e perl6 -vr t/
- echo Running spesh disabled && PERL6LIB=$PWD/blib/lib MVM_SPESH_DISABLE=1 prove -e perl6 --ll-exception --profile-filename out.json -vr t/
-cat out.json
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_e8f54b4675bd_key -iv $encrypted_e8f54b4675bd_iv
  -in login.pl.enc -out t/login.pl -d
- mkdir ~/.lacuna_cookbuk
- cp t/login.pl ~/.lacuna_cookbuk/
