language: perl6
env:
 MVM_SPESH_DISABLE=1
install:
- rakudobrew build-panda
- panda --notests installdeps .
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_e8f54b4675bd_key -iv $encrypted_e8f54b4675bd_iv
  -in login.pl.enc -out t/login.pl -d
- mkdir ~/.lacuna_cookbuk
- cp t/login.pl ~/.lacuna_cookbuk/
