=begin pod



=head1 NAME LacunaCookbuk

Client.pm aka client.pl is main client for LacunaCookbuk

=head1 SYNOPSIS

Script helps L<B<https://us1.lacunaexpanse.com/>> players doing boring tasks like moving glyphs to one place that can make plans from them or searching where excess fighters can be put. The intention was putting perl6 into life. 

I use parrot backend for building this. 

All planets must have Trade Ministry, Intelligence Ministry and Archaeology Ministry. All space stations must have Parliament.

Compilation:

	$ panda install JSON::RPC
	$ panda install ufo
	$ panda install Form 

	$ git clone https://github.com/teodozjan/lacuna-cookbuk.git
	$ cd lacuna-cookbuk
	$ cp lib/LacunaCookbuk/SampleConfig.pm lib/LacunaCookbuk/Config.pm 
	$ editor lib/LacunaCookbuk/Config.pm 

	$ ufo
	$ make install


Fun with client:

    $ perl6 bin/client.pl --taks=all


Things that seem to work:

=item Caching planets and its buildings
=item Finding out what ores are on planets
=item Checking whether space port or intelligence ministries are full
=item Moving glyphs and plans between planets
=item Assembling halls
=item Upgrading rules
=item Find ineffective ships to replace
=item Automatic voting in parliament
=item List incoming ships
=item Delete Parliament messages automatically 

=head1 TODO Functions

=item Specify different upgrade order for different planets
=item Autobalance supply chains (send to home planet)
=item Autobalance home planet (if all supply chains will become 0 it won't go negative on happiness)
=item Multi user voting for aliance master

=head1 TODO Code smell

=item Remove logic from Model classess
=item Don't give bodybuilder everyone
=item Change loops to list generic functions where possible
=item Due to perl6 compilation has no spec yet and diffrenet parrot backends treat differently INIT {} blocks it is not safe to declare class attributes that do time or disk consuming operations 

=end pod