=begin pod

=head1 Model

Model contains choosen attributes inisde classes and and low level methods to contact game servers like get mentioned attributes or do something. No decisions or logic should be found here.

=head1 Logic

=head2 Ambassador	

Contains methods allowing B<Parliament> operations. 

=head2 BodyBuilder

Supplies building list and saves it to disk

=head2 Chairman	

P<doc:LacunaCookbuk::Logic::Chairman>

=head2 Commander

L<doc:LacunaCookbuk::Logic::Commander>

=head2 IntelCritic

L<doc:LacunaCookbuk::Logic::IntelCritic>

=head2 OreCritic

Displays the ore

=head2 PlanMaker

L<doc:LacunaCookbuk::Logic::PlanMaker>

=head2 Secretary

L<doc:LacunaCookbuk::Logic::Secretary>

=head2 ShipCritic

Takes care of ships

=head2 Transporter

Allows to send cargo with fastest ship available
	
=end pod
